name: ctt-personal-devnet
on:
  push:
    branches:
      - bkdf-design
  pull_request_target:
  workflow_dispatch:
jobs:
  deploy-ui-to-devnet-and-testnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        id: ctt-personal-action-devnet
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.CTT_PERSONAL_PROJECT_ID }}
          working-directory: axelarjs-ui
