name: ctt-personal-devnet
on:
  push:
    branches:
      - keplr
  pull_request_target:
  workflow_dispatch:
jobs:
  ctt-personal-devnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        id: ctt-personal-action-devnet
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.CTT_PERSONAL_VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.CTT_PERSONAL_VERCEL_PROJECT_ID }}
          alias-domains: |
            canh-testing.vercel.app